---
abstract: 'build & release a distribution like jquelin'
author:
  - 'Jerome Quelin'
build_requires:
  Module::Build: 0.35
configure_requires:
  Module::Build: 0.35
generated_by: 'Dist::Zilla version 1.093400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-JQUELIN
provides:
  Dist::Zilla::PluginBundle::JQUELIN:
    file: lib/Dist/Zilla/PluginBundle/JQUELIN.pm
    version: 1.100060
requires:
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::Role::PluginBundle: 0
  English: 0
  File::Find: 0
  Module::Build: 0
  Moose: 0
  Moose::Autobox: 0
  Test::More: 0
  perl: 5.008
resources:
  MailingList: http://www.listbox.com/subscribe/?list_id=139292
  homepage: http://search.cpan.org/dist/Dist-Zilla-PluginBundle-JQUELIN
  repository: http://github.com/jquelin/dist-zilla-pluginbundle-jquelin
version: 1.100060
