---
abstract: 'build & release a distribution like jquelin'
author:
  - 'Jerome Quelin'
build_requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::More: 0.94
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101612, CPAN::Meta::Converter version 2.101610'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-JQUELIN
provides:
  Dist::Zilla::PluginBundle::JQUELIN:
    file: lib/Dist/Zilla/PluginBundle/JQUELIN.pm
    version: 1.101620
requires:
  Class::MOP: 0
  Dist::Zilla::Plugin::AutoPrereq: 0
  Dist::Zilla::Plugin::AutoVersion: 0
  Dist::Zilla::Plugin::Bugtracker: 0
  Dist::Zilla::Plugin::CheckChangeLog: 0
  Dist::Zilla::Plugin::CompileTests: 1.100220
  Dist::Zilla::Plugin::CriticTests: 0
  Dist::Zilla::Plugin::ExecDir: 0
  Dist::Zilla::Plugin::ExtraTests: 0
  Dist::Zilla::Plugin::GatherDir: 0
  Dist::Zilla::Plugin::HasVersionTests: 0
  Dist::Zilla::Plugin::Homepage: 0
  Dist::Zilla::Plugin::KwaliteeTests: 0
  Dist::Zilla::Plugin::License: 0
  Dist::Zilla::Plugin::Manifest: 0
  Dist::Zilla::Plugin::ManifestSkip: 0
  Dist::Zilla::Plugin::MetaConfig: 0
  Dist::Zilla::Plugin::MetaJSON: 0
  Dist::Zilla::Plugin::MetaProvides::Package: 0
  Dist::Zilla::Plugin::MetaTests: 0
  Dist::Zilla::Plugin::MetaYAML: 0
  Dist::Zilla::Plugin::MinimumVersionTests: 0
  Dist::Zilla::Plugin::ModuleBuild: 0
  Dist::Zilla::Plugin::NextRelease: 2.101230
  Dist::Zilla::Plugin::PkgVersion: 0
  Dist::Zilla::Plugin::PodCoverageTests: 0
  Dist::Zilla::Plugin::PodSyntaxTests: 0
  Dist::Zilla::Plugin::PodWeaver: 0
  Dist::Zilla::Plugin::PortabilityTests: 0
  Dist::Zilla::Plugin::Prepender: 1.100130
  Dist::Zilla::Plugin::PruneCruft: 0
  Dist::Zilla::Plugin::Readme: 0
  Dist::Zilla::Plugin::ReportVersions: 0
  Dist::Zilla::Plugin::Repository: 0
  Dist::Zilla::Plugin::ShareDir: 0
  Dist::Zilla::Plugin::TaskWeaver: 0
  Dist::Zilla::Plugin::UnusedVarsTests: 0
  Dist::Zilla::Plugin::UploadToCPAN: 0
  Dist::Zilla::PluginBundle::Git: 0
  Dist::Zilla::Role::PluginBundle: 0
  Moose: 0
  Moose::Autobox: 0
  perl: 5.008
resources:
  X_mailing_list: http://www.listbox.com/subscribe/?list_id=139292
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-JQUELIN
  homepage: http://search.cpan.org/dist/Dist-Zilla-PluginBundle-JQUELIN/
  repository: http://github.com/jquelin/dist-zilla-pluginbundle-jquelin
version: 1.101620
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::AutoVersion
      name: '@JQUELIN/AutoVersion'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@JQUELIN/GatherDir'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@JQUELIN/CompileTests'
      version: 1.101600
    -
      class: Dist::Zilla::Plugin::CriticTests
      name: '@JQUELIN/CriticTests'
      version: 1.100140
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@JQUELIN/HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@JQUELIN/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@JQUELIN/MetaTests'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@JQUELIN/MinimumVersionTests'
      version: 1.101421
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@JQUELIN/PodCoverageTests'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@JQUELIN/PodSyntaxTests'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: '@JQUELIN/PortabilityTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::ReportVersions
      name: '@JQUELIN/ReportVersions'
      version: 1.101600
    -
      class: Dist::Zilla::Plugin::UnusedVarsTests
      name: '@JQUELIN/UnusedVarsTests'
      version: 1.100860
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@JQUELIN/PruneCruft'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@JQUELIN/ManifestSkip'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: '@JQUELIN/AutoPrereq'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@JQUELIN/ExtraTests'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@JQUELIN/NextRelease'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@JQUELIN/PkgVersion'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@JQUELIN/PodWeaver'
      version: 3.101530
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@JQUELIN/Prepender'
      version: 1.101590
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@JQUELIN/ExecDir'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@JQUELIN/ShareDir'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@JQUELIN/Bugtracker'
      version: 1.101490
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@JQUELIN/Homepage'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@JQUELIN/Repository'
      version: 0.13
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@JQUELIN/MetaProvides::Package'
      version: 1.10027802
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@JQUELIN/MetaConfig'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::License
      name: '@JQUELIN/License'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@JQUELIN/MetaYAML'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@JQUELIN/MetaJSON'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@JQUELIN/ModuleBuild'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@JQUELIN/Readme'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@JQUELIN/Manifest'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@JQUELIN/CheckChangeLog'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@JQUELIN/UploadToCPAN'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@JQUELIN/Git/Check'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@JQUELIN/Git/Commit'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@JQUELIN/Git/Tag'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@JQUELIN/Git/Push'
      version: 1.101330
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.101612
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.101612
  zilla:
    class: Dist::Zilla
    config:
      is_trial: 0
    version: 4.101612
